server:
  port: 8082
spring:
  application:
    name: cloud-consumer-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://eureka7001.com:7001/,http://eureka7002.com:7002/
  instance:
    ip-address: true
    instance-id: cloud-consumer8082